# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=40)),
                ('buyer', models.CharField(max_length=40)),
                ('src1', models.CharField(max_length=80)),
                ('src2', models.CharField(max_length=80)),
                ('src3', models.CharField(max_length=80)),
                ('src4', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('pri', models.CharField(max_length=40)),
                ('original_price', models.CharField(max_length=40)),
                ('index1', models.CharField(max_length=80)),
                ('index2', models.CharField(max_length=80)),
                ('index3', models.CharField(max_length=80)),
                ('index4', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=40)),
                ('buyer', models.CharField(max_length=40)),
                ('src1', models.CharField(max_length=80)),
                ('src2', models.CharField(max_length=80)),
                ('src3', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('original_price', models.CharField(max_length=40)),
                ('index1', models.CharField(max_length=80)),
                ('index2', models.CharField(max_length=80)),
                ('index3', models.CharField(max_length=80)),
            ],
        ),
    ]
